config/routes.rb
Rails.application.routes.draw do
  get 'posts/create'
  devise_for :users, controllers: { sessions: 'users/sessions' }
  get "/home", to: 'users#home'
  get "/profile", to: 'users#profile'
  get "/users/:id/profile", to: 'users#profile'
  get "/profile/:option", to: 'users#profile'
  patch "/profile/update_description", to: 'users#update_profile_description'
  post "/profile/update_avatar", to: 'users#update_avatar'
  root "users#home"
  resources :posts, only: [:create, :destroy]
  resources :comments, only: [:create, :destroy]
  post "/user_friend/request_friend", to: "user_friend#request_friend"
  post "/user_friend/accept_friend", to: "user_friend#accept_friend"
  post "/user_friend/reject_friend", to: "user_friend#reject_friend"
  post "/user_friend/remove_friend", to: "user_friend#remove_friend"
  resources :likes, only: [:create]
  post "/likes/destroy", to: "likes#destroy"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
  has_one_attached :avatar
  validates :name, presence: true

  def own_and_friends_posts
    friend_ids = self.friends.map { |friend| friend['friend_id']} 
    friend_ids << self.id
    friend_ids_string = friend_ids.join(', ')
    Post.joins(:user).select("posts.id as id", :text, "users.id as user_id", "users.name as user_name", :created_at).order(created_at: :desc).where("users.id in ( #{friend_ids_string} )")  
  end

  def own_posts
    Post.joins(:user).select("posts.id as id", :text, "users.id as user_id", "users.name as user_name", :created_at).order(created_at: :desc).where(user_id: self.id)  
  end

  def friends
    sql = basic_friends_query + "
    AND
    accepted = true
    "
    ActiveRecord::Base.connection.execute(sql)
  end

  def pending_friend_requests
    sql = "SELECT Friends.email, Friends.id
    FROM Users 
    JOIN User_Friend on (Users.id = requestee_id)
    JOIN Users as Friends on (Friends.id = requester_id)
    WHERE Users.id = #{self.id} and User_Friend.accepted = false
    "
    ActiveRecord::Base.connection.execute(sql)
  end

  def suggested_friends
    # First, get all of the friends
    sql = "SELECT email, id
    FROM Users
    WHERE NOT EXISTS (
      SELECT 1 FROM ( " + basic_friends_query + " AND friend_id = Users.id ) as all_friends
    ) AND Users.id != #{self.id}"
    ActiveRecord::Base.connection.execute(sql)
  end

  private

  def basic_friends_query
    "SELECT * FROM (
      SELECT users.id as user_id, friends.id as friend_id, friends.email as friend_email, user_friend.accepted
      FROM Users 
      JOIN User_Friend on (Users.id = requester_id)
      JOIN Users as Friends on (Friends.id = requestee_id)
      UNION ALL
      SELECT users.id as user_id, friends.id as friend_id, friends.email as friend_email, user_friend.accepted
      FROM Users 
      JOIN User_Friend on (Users.id = requestee_id)
      JOIN Users as Friends on (Friends.id = requester_id)
      ) as all_friends
      WHERE user_id = #{self.id}
    "
  end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  skip_before_action :authenticate_user!, only: [:new, :create]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  skip_before_action :authenticate_user!, only: [:new, :create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def home
    if params.key?("id")
      @user = User.find(params["id"])
    else
      @user = current_user
    end
    @posts = @user.own_and_friends_posts   
  end

  def profile
    if params.key?("id")
      @user = User.find(params["id"])
    else
      @user = current_user
    end
    @posts = @user.own_posts

  end

  def update_profile_description
    if current_user.update(params.require(:user).permit(:description))
      redirect_to '/profile'
    else
      render '/profile/edit_description'
    end
  end

  def update_avatar
    if current_user.avatar.attach(params[:avatar])
      redirect_to '/profile'
    else
      render '/profile'
    end
  end

end

app/views/users/_feed.html.erb
<% if @user == current_user %>
  <div class="box">
    <%= form_for :post, url: posts_path do |f| %>
      <div class="field">
        <label class="label">What's on your mind?</label>
        <%= f.text_area :text, class: "textarea", placeholder: "Your awesome thoughts..."%>
      </div>
      <%= hidden_field_tag 'return_url', request.original_url %>
      <%= f.submit "Post",  class: "button is-link" %>
    <% end %>
  </div>
<% end %>

<% @posts.each do |post| %>
  <div class="box">
    <article class="media">
      <figure class="media-left">
        <p class="image is-48x48 is-square">
          <% user = User.find(post.user_id) %>
          <% if user.avatar.attached? %>
            <%= image_tag user.avatar, class: "is-rounded" %>
          <% else %>
            <img src="https://bulma.io/images/placeholders/128x128.png", class="is-rounded">
          <% end %>
        </p>
      </figure>
      <div class="media-content">
        <div class="content">
          <p>
            <%= link_to "/users/#{post.user_id}/profile", class: "content has-text-black" do %>
              <strong><%= post.user_name %></strong>
            <% end %>
            <br>
            <small><%= post.created_at %></small>
          </p>
        </div>
      </div>
      <% if user == current_user %>
        <div class="media-right">
          <div class="media-content">
            <div class="content">
              <%= link_to "Delete Post", post_path(post),
                  method: :delete,
                  data: { confirm: "Are you sure you want to delete this post?" } , 
                  class: "button is-danger is-small" 
              %>
            </div>
          </div>
        </div>
      <% end %>
    </article>

    <div class="block">
      <p><%= post.text %></p>
    </div>

    <div class="block">
      <nav class="level">
        <div class="level-left">
          <div class="level-item">
            <% if Like.find_by(post_id: post.id, user_id: current_user.id).blank? %>
              <%= form_for :like, url: likes_path do |f| %>
                <%= f.hidden_field :post_id, :value => post.id %>
                <%= f.hidden_field :user_id, :value => current_user.id %>
                <%= hidden_field_tag 'return_url', request.original_url %>
                <button class="button is-outlined" type="submit">
                  <span class="icon is-small">
                    <i class="fas fa-thumbs-up"></i>
                  </span>
                </button>
              <% end %>
            <% else %> 
              <%= form_with url: '/likes/destroy' do |f| %>
                <%= f.hidden_field :post_id, :value => post.id %>
                <%= f.hidden_field :user_id, :value => current_user.id %>
                <%= hidden_field_tag 'return_url', request.original_url %>
                <button class="button is-link" type="submit">
                  <span class="icon is-small">
                    <i class="fas fa-thumbs-up"></i>
                  </span>
                </button>
              <% end %>
            <% end %>
          </div>
          <div class="level-item">
            <%= Like.where(post_id: post.id).count %>
          </div>
        </div>
      </nav>
    </div>

    <% post.comments.each do |comment| %>
      <% comment_user = comment.user %>
      <div class="block">
        <article class="media">
          <figure class="media-left">
            <p class="image is-48x48 is-square">
              <% if comment_user.avatar.attached? %>
                <%= image_tag comment_user.avatar, class: "is-rounded" %>
              <% else %>
                <img src="https://bulma.io/images/placeholders/128x128.png", class="is-rounded">
              <% end %>
            </p>
          </figure>
          <div class="media-content has-background-grey-lighter">
            <div class="content">
              <p>
                <strong><%= comment_user.name %></strong>
                <br>
                <%= comment.text %>
              </p>
            </div>
          </div>
          <% if comment_user == current_user %>
            <div class="media-right">
              <div class="media-content">
                <div class="content">
                  <%= link_to "Delete", comment_path(comment),
                      method: :delete,
                      data: { confirm: "Are you sure you want to delete this comment?" } , 
                      class: "button is-danger is-small" 
                  %>
                </div>
              </div>
            </div>
          <% end %>
        </article>
      </div>
    <% end %>

    <article class="media">
      <figure class="media-left">
        <p class="image is-48x48 is-square">
          <% if current_user.avatar.attached? %>
            <%= image_tag current_user.avatar, class: "is-rounded" %>
          <% else %>
            <img src="https://bulma.io/images/placeholders/128x128.png", class="is-rounded">
          <% end %>
        </p>
      </figure>
      <div class="media-content">
        <div class="content">
          <%= form_for :comment, url: comments_path do |f| %>
            <div class="field">
              <%= f.text_field :text, class: "input", type: "text", placeholder: "Write a comment..."%>
            </div>
            <%= f.hidden_field :post_id, :value => post.id %>
            <%= hidden_field_tag 'return_url', request.original_url %>
          <% end %>
        </div>
      </div>
    </article> 
  </div>
<% end %>

app/views/users/_friends.html.erb
<div class="block">
  <div class="block">
    <strong>Your friends</strong>
  </div>
  <% current_user.friends.each do |friend| %>
    <% friend = User.find(friend['friend_id'])%>
    <div class="block">
      <article class="media">
        <figure class="media-left">
          <p class="image is-48x48 is-square">
            <% if friend.avatar.attached? %>
              <%= image_tag friend.avatar, class: "is-rounded"  %>
            <% else %>
              <img src="https://bulma.io/images/placeholders/128x128.png", class="is-rounded">
            <% end %>
          </p>
        </figure>
        <div class="media-content">
          <%= link_to "/users/#{friend.id}/profile", class: "button is-light" do %>
            <%= limit_string(friend.name) %>
          <% end %>
        </div>
        <div class="media-right">
          <div class="media-content">
            <div class="content">
              <%= form_with url: '/user_friend/remove_friend' do |f| %>
                <%= f.hidden_field :friend_id, :value => friend.id %>
                <%= hidden_field_tag 'return_url', request.original_url %>
                <%= f.submit "Unfriend", class: "button is-danger is-small"%>
              <% end %>
            </div>
        </div>
      </article> 
    </div>
  <% end %>
</div>

<div class="block">
  <div class="block">
    <strong>Friend requests</strong>
  </div>
  <% current_user.pending_friend_requests.each do |friend| %>
    <% friend = User.find(friend['id'])%>
    <div class="block">
      <article class="media">
        <figure class="media-left">
          <p class="image is-48x48 is-square">
            <% if friend.avatar.attached? %>
              <%= image_tag friend.avatar, class: "is-rounded"  %>
            <% else %>
              <img src="https://bulma.io/images/placeholders/128x128.png", class="is-rounded">
            <% end %>
          </p>
        </figure>
        <div class="media-content">
          <%= link_to "/users/#{friend.id}/profile", class: "button is-light" do %>
            <%= limit_string(friend.name) %>
          <% end %>
        </div>
        <div class="media-right">
          <div class="media-content">
            <div class="content">
              <%= form_for :user_friend, url: '/user_friend/accept_friend' do |f| %>
                <%= f.hidden_field :requester_id, :value => friend.id %>
                <%= hidden_field_tag 'return_url', request.original_url %>
                <%= f.submit "Accept", class: "button is-success is-small" %>
              <% end %>
            </div>
            <div class="content">
              <%= form_for :user_friend, url: '/user_friend/reject_friend' do |f| %>
                <%= f.hidden_field :requester_id, :value => friend.id %>
                <%= hidden_field_tag 'return_url', request.original_url %>
                <%= f.submit "Reject", class: "button is-danger is-small" %>
              <% end %>
            </div>
          </div>
        </div>
      </article> 
    </div>
  <% end %>
</div>

<div class="block">
  <div class="block">
    <strong>Suggested friends</strong>
  </div>
  
  <% current_user.suggested_friends.each do |friend| %>
    <% friend = User.find(friend['id'])%>
    <div class="block">
      <article class="media">
        <figure class="media-left">
          <p class="image is-48x48 is-square">
            <% if friend.avatar.attached? %>
              <%= image_tag friend.avatar, class: "is-rounded"  %>
            <% else %>
              <img src="https://bulma.io/images/placeholders/128x128.png", class="is-rounded">
            <% end %>
          </p>
        </figure>
        <div class="media-content">
          <%= link_to "/users/#{friend.id}/profile", class: "button is-light" do %>
            <%= limit_string(friend.name, 12) %>
          <% end %>
        </div>
        <div class="media-right">
          <div class="media-content">
            <div class="content">
              <%= form_for :user_friend, url: '/user_friend/request_friend' do |f| %>
                <%= f.hidden_field :requestee_id, :value => friend.id %>
                <%= hidden_field_tag 'return_url', request.original_url %>
                <%= f.submit "Request friend", class: "button is-info is-small" %>
              <% end %>
            </div>
          </div>
        </div>
      </article> 
    </div>
  <% end %>
</div>

app/views/users/_personal_info.html.erb
<section class="section has-text-centered">
  <div class="container is-max-desktop">
    <div class="block">
      <% if @user.avatar.attached? %>
        <%= image_tag @user.avatar, size: "300"%>
      <% else %>
        <img src="https://versions.bulma.io/0.7.0/images/placeholders/128x128.png", size="300">
      <% end %>
      <% if @user == current_user %>
        <% if params[:option] == 'edit_avatar' %>
          <%= form_with url: "/profile/update_avatar" do |f| %>
            <%= f.file_field :avatar, accept: "image/*" %><br>
            <%= f.submit "Submit", class: "button is-small"%>
            <%= link_to "/profile", class: "button is-small" do %>
              Cancel
            <% end %>
          <% end %>
        <% else %>
          <%= form_with url: "/profile/edit_avatar", method: 'get' do |f| %>
            <%= f.submit "Edit Profile Photo", class: "button is-small"%>
          <% end %>
        <% end %>
      <% end %>
    </div>
    <div class="block">
      <div class="content">
        <h1><%= @user.name %></h1>
      </div>
    </div>
    <div class="block">
      <% if @user == current_user %>
        <% if params[:option] == 'edit_description' %>
          <%= form_for @user, url: "/profile/update_description" do |f| %>
            <%= f.text_area :description, class: "textarea"  %>
            <%= f.submit "Update", class: "button is-small"%>
            <%= link_to "/profile", class: "button is-small" do %>
              Cancel
            <% end %>
          <% end %>
        <% else %>
          <p><%= @user.description %></p>
          <%= form_with url: "/profile/edit_description", method: 'get' do |f| %>
            <%= f.submit "Edit Profile Description", class: "button is-small"%>
          <% end %>
        <% end %>
      <% else %>
        <p><%= @user.description %></p>
      <% end %>
    </div>
  </div>
</section>

app/views/users/home.html.erb
<% content_for :friends do %>
  <%= render "friends" %>
<% end %>


<%= render "feed" %>

app/views/users/profile.html.erb
<% content_for :top do %>
  <%= render "personal_info" %>
<% end %>

<% content_for :friends do %>
  <%= render "friends" %>
<% end %>

<%= render "feed" %>